### ISSUE TITLE
Clean up data of junks

### ISSUE THREAD

**Issue by Proluiz** [ThetaTeam/theta#1]
Updated to the most recent errors of load
![screenshot_doom_20150707_123205](https://cloud.githubusercontent.com/assets/6380147/8550037/7de47b72-24a4-11e5-91ca-c1c7a37595cf.png)

Mods that have errors consume 1ms of time to build up a good example is try to load a skulltag map whitout skulltage data it take minutes to load, so kill that erros make loading more fast, make easy to dont happen crashs, and well make more cool see that mod dont have issues.

**Comment by PlusGit** [comment]
IMO this is more than an enhancement than a bug. Changed labels accordingly.

**Comment by PlusGit** [comment]
Commit efd71e9 is a minor fix.

**Comment by Proluiz** [comment]
![screenshot_doom_20150707_123205](https://cloud.githubusercontent.com/assets/6380147/8550037/7de47b72-24a4-11e5-91ca-c1c7a37595cf.png)
updated the 1st post

**Comment by Proluiz** [comment]
![screenshot_doom_20150707_154659](https://cloud.githubusercontent.com/assets/6380147/8554354/d6b139aa-24bf-11e5-98cb-4c80c8dfed3c.png)
done.

**Comment by Proluiz** [comment]
Going open again since we still have few junks happening around
