### ISSUE TITLE
C4 wrong real dimensions

### ISSUE THREAD

**Issue by Proluiz** [ThetaTeam/theta#26]
both open gl and software they heights are fucked up.
also in opengl c4 looks like buried
![screenshot_doom_20150717_141749](https://cloud.githubusercontent.com/assets/6380147/8753689/127487a4-2c94-11e5-9436-6598b2bfc32a.png)
![screenshot_doom_20150717_141517](https://cloud.githubusercontent.com/assets/6380147/8753690/12bb8d0c-2c94-11e5-9c56-24edc1deb791.png)

also his flying version is not 3d in opengl

**Comment by OmicronWhite** [comment]
Changing the scale for thrown C4 to 0.15 and armed C4 to 0.08 makes it look a more normal size

![screenshot_doom_20151212_124902](https://cloud.githubusercontent.com/assets/13123325/11761522/c7ff1e28-a0ce-11e5-9114-e85a37e06b6a.png)

**Comment by PlusGit** [comment]
Fixed in 7c474b4
